#!/bin/bash
source ~/.bashrc
                              # TRAINING SEQUENCE
#model_name_1=spacy_clf_A      # ARTICLES
#model_loc_2=spacy_clf_AR      # ARTICLES -> REDDIT
#model_loc_3=spacy_clf_ARA     # ARTICLES -> REDDIT -> ARTICLES



                              # DATA NAMES
#articles.pkl   # ARTICLES
#reddit.pkl     # REDDIT
#holdout.pkl    # HOLDOUT

#python spacy_textcat.py
python spacy_textcat.py -d articles.pkl -m spacey_2.0
