#!/bin/bash
source ~/.bashrc
                              # TRAINING SEQUENCE
#model_name_1=spacy_clf_A      # ARTICLES
#model_loc_2=spacy_clf_AR      # ARTICLES -> REDDIT
#model_loc_3=spacy_clf_ARA     # ARTICLES -> REDDIT -> ARTICLES



                              # DATA NAMES
#articles.pkl   # ARTICLES
#reddit.pkl     # REDDIT
#holdout.pkl    # HOLDOUT

#python spacy_textcat.py
#python spacy_textcat.py -d articles.pkl -m spacy_2.0 -o spacy_2.1 -rs none
#python spacy_textcat.py -d articles.pkl -m spacy_2.1 -o spacy_2.2 -rs under
# python spacy_textcat.py -d articles.pkl -m spacy_2.2 -o spacy_2.3 -rs over \
#   -ep 2
#python spacy_textcat.py -d reddit.pkl -m spacy_2.3 -o spacy_2.4 -rs none
# python spacy_textcat.py -d articles.pkl -m spacy_2.5 -o spacy_2.5 -rs under \
    # -tr -minb 64.0 -maxb 256.0
#

# python spacy_textcat.py -d articles.pkl -m spacy-3.a -o spacy-3.a -CVI 2000 -rs under \
#     -minb 4.0 -maxb 64.0
#
# python spacy_textcat.py -d articles.pkl -m spacy-3.a -o spacy-3.aa -CVI 2000 -rs over \
#     -minb 32.0 -maxb 64.0
#
# python spacy_textcat.py -d reddit.pkl -m spacy-3.aa -o spacy-3.aar -CVI 2000 -rs none \
#     -minb 32.0 -maxb 64.0
#
# python spacy_textcat.py -d articles.pkl -m spacy-3.aar -o spacy-3.aaara -CVI 2000 -rs under \
#     -minb 32.0 -maxb 64.0
#
#
#
# python spacy_textcat.py -d reddit.pkl -m spacy-4.r -o spacy-4.r -CVI 2000 -rs none \
#     -minb 4.0 -maxb 64.0
#
# python spacy_textcat.py -d articles.pkl -m spacy-4.r -o spacy-4.ra -CVI 2000 -rs under \
#     -minb 32.0 -maxb 64.0
#
# python spacy_textcat.py -d articles.pkl -m spacy-4.ra -o spacy-4.raaaa -CVI 2000 -rs over \
#     -minb 64.0 -maxb 64.0 -ep 3
#
#
#
# python spacy_textcat.py -d articles.pkl -m spacy-5.a10 -CVI 2000 -rs over \
#     -minb 4.0 -maxb 64.0 -ep 10
#
#
#
# python spacy_textcat.py -d articles.pkl -m spacy-6.a -CVI 2000 -rs over \
#     -minb 4.0 -maxb 64.0 -ep 2 -do 0.6
#
# python spacy_textcat.py -d articles.pkl -m spacy-6.a -o spacy-6.aa -CVI 2000 -rs over \
#     -minb 4.0 -maxb 64.0 -ep 2 -do 0.4
#
# python spacy_textcat.py -d articles.pkl -m spacy-6.aa -o spacy-6.aaa -CVI 2000 -rs over \
#     -minb 4.0 -maxb 64.0 -ep 2 -do 0.2
#
# python spacy_textcat.py -d articles.pkl -m spacy-6.aaa -o spacy-6.aaaa -CVI 2000 -rs over \
#     -minb 4.0 -maxb 64.0 -ep 2 -do 0.1

# python spacy_textcat.py articles_no_center.pkl -m spacy-7.a -o spacy-7.a -CVI 2000 -rs over \
#     -minb 4.0 -maxb 64.0 -ep 2 -do 0.7
#
# python spacy_textcat.py articles_no_center.pkl -m spacy-7.a -o spacy-7.aa -CVI 2000 -rs over \
#     -minb 4.0 -maxb 64.0 -ep 2 -do 0.6
#
# python spacy_textcat.py articles_no_center.pkl -m spacy-7.aa -o spacy-7.aaa -CVI 2000 -rs over \
#     -minb 4.0 -maxb 64.0 -ep 2 -do 0.5
#
# python spacy_textcat.py articles_no_center.pkl -m spacy-7.aaa -o spacy-7.aaaa -CVI 2000 -rs over \
#     -minb 4.0 -maxb 64.0 -ep 2 -do 0.4
#
#
# python spacy_textcat.py articles_no_center.pkl -m spacy-8.a -o spacy-8.a -CVI 2000 -rs over \
#     -minb 4.0 -maxb 64.0 -ep 2 -do 0.6
#
# python spacy_textcat.py reddit_no_center.pkl -m spacy-8.a -o spacy-8.ar -CVI 2000 -rs choose_n \
#     -maxN 4000 -minb 4.0 -maxb 64.0 -ep 1 -do 0.6
#
# python spacy_textcat.py articles_no_center.pkl -m spacy-8.ar -o spacy-8.ara -CVI 2000 -rs over \
#     -minb 4.0 -maxb 64.0 -ep 4 -do 0.5
#
# #really good right here
#
# python spacy_textcat.py reddit_no_center.pkl -m spacy-8.ara -o spacy-8.arar -CVI 2000 -rs choose_n \
#     -maxN 6000 -minb 4.0 -maxb 64.0 -ep 1 -do 0.6
#
# python spacy_textcat.py articles_no_center.pkl -m spacy-8.arar -o spacy-8.arara -CVI 2000 -rs over \
#     -minb 4.0 -maxb 64.0 -ep 8 -do 0.5
#
# python spacy_textcat.py articles.pkl -m spacy-9.a -o spacy-9.a -CVI 2000 -rt -rs under
#
# python spacy_textcat.py reddit.pkl -m spacy-9.a -o spacy-9.ar -CVI 2000 -rs choose_n
#
# python spacy_textcat.py articles.pkl -m spacy-9.ar -o spacy-9.ara -CVI 2000 -rs under
#
# #ran to here




# python spacy_textcat.py articles.pkl -m spacy-10.a -CVI 2000 -rs over -fb
#
# python spacy_textcat.py reddit.pkl -m spacy-10.a -o spacy-10.ar -CVI 2000 -rs choose_n
#
# python spacy_textcat.py articles.pkl -m spacy-10.ar -o spacy-10.ara -CVI 2000 -rs under -fb
#
# python spacy_textcat.py reddit.pkl -m spacy-10.ara -CVI 2000 -rs choose_n -maxN 2000
#
# python spacy_textcat.py articles.pkl -m spacy-10.ara -CVI 2000 -rs under -fb
#
# python spacy_textcat.py reddit.pkl -m spacy-10.ara -CVI 2000 -rs choose_n
#
# python spacy_textcat.py articles.pkl -m spacy-10.ara -CVI 2000 -rs under -fb

#python spacy_textcat.py reddit.pkl -m spacy-4.r -o spacy-11.rr -minb 4.0 -maxb 128.0 -do 0.5 -rs under
# python spacy_textcat.py reddit.pkl -m spacy-11.rr -o spacy-11.r3 -minb 4.0 -maxb 128.0 -do 0.3 -rs under
# python spacy_textcat.py reddit.pkl -m spacy-11.r3 -o spacy-11.r4 -minb 4.0 -maxb 128.0 -do 0.2 -rs under
# python spacy_textcat.py reddit.pkl -m spacy-11.r4 -o spacy-11.r5 -minb 4.0 -maxb 128.0 -do 0.1 -rs under
#
python spacy_textcat.py mixed.pkl -m spacy-11.r5 -o spacy-11.r5m1 -minb 4.0 -maxb 128.0 -do 0.5 -rs under
python spacy_textcat.py mixed.pkl -m spacy-11.r5m1 -o spacy-11.r5m2 -minb 4.0 -maxb 128.0 -do 0.3 -rs under
python spacy_textcat.py mixed.pkl -m spacy-11.r5m2 -o spacy-11.r5m3 -minb 4.0 -maxb 128.0 -do 0.2 -rs under

rm ../data/tag_dir/mixed_tags.npy

python spacy_textcat.py mixed.pkl -m spacy-11.r5 -o spacy-11.r5m1v2 -minb 4.0 -maxb 128.0 -do 0.5 -rs under
python spacy_textcat.py mixed.pkl -m spacy-11.r5m1v2 -o spacy-11.r5m2v2 -minb 4.0 -maxb 128.0 -do 0.3 -rs under
python spacy_textcat.py mixed.pkl -m spacy-11.r5m2v2 -o spacy-11.r5m3v2 -minb 4.0 -maxb 128.0 -do 0.2 -rs under

rm ../data/tag_dir/mixed_tags.npy

python spacy_textcat.py mixed.pkl -m spacy-11.r5 -o spacy-11.r5m1v3 -minb 4.0 -maxb 128.0 -do 0.5 -rs under
python spacy_textcat.py mixed.pkl -m spacy-11.r5m1v3 -o spacy-11.r5m2v3 -minb 4.0 -maxb 128.0 -do 0.3 -rs under
python spacy_textcat.py mixed.pkl -m spacy-11.r5m2v3 -o spacy-11.r5m3v3 -minb 4.0 -maxb 128.0 -do 0.2 -rs under


#
