#!/bin/bash

src_path='/home/zachary/dsi/capstone/src'
sense2vec_path='/home/zachary/dsi/sense2vec/bin'
data_path='/home/zachary/dsi/capstone/data/articles2'

vec_size='128'

python $src_path/formatter.py
python $sense2vec_path/merge_text.py $data_path/articles.npz $data_path/annotated_text
python $sense2vec_path/train_word2vec.py $data_path/annotated_text $data_path/trained_model -d $vec_size
python $sense2vec_path/gensim2sense.py $data_path/trained_model $data_path/vector_map -d $vec_size
